### ISSUE TITLE
How to get an .oecoreplugin file?

### ISSUE THREAD

**Issue by cedricdelpoux** [MaddTheSane/DuckStation-Core#14]
Hi, Thank you for making a Duckstation core for OpenEmu.

How to get .oecoreplugin core file to add to OpenEmu?

There is no Readme.
Thank you

**Comment by MaddTheSane** [comment]
Clone OpenEmu.
`git clone --recursive https://github.com/OpenEmu/OpenEmu.git`
You might want to selectively clone submodules:
```bash
git clone https://github.com/OpenEmu/OpenEmu.git
cd OpenEmu
git submodule update --init --recursive OpenEmu-SDK OpenEmuKit
```

Then clone the DuckStation core inside of the OpenEmu directory.
`cd OpenEmu; git clone --recursive https://github.com/MaddTheSane/DuckStation-Core.git`

Open `OpenEmu.xcworkspace` with Xcode.
Open the DuckStation-Core directory.
Drag the `DuckStation.xcodeproj` file into the Xcode window that represents `OpenEmu.xcworkspace`. Make sure to not drop it within another Xcode project, but the top level workspace.

Create a new scheme. Under target, select *Build & Install DuckStation*.
Edit the new scheme: Set the Build Configuration of Run to Release.

This is how I have it set-up.

**Comment by cedricdelpoux** [comment]
Thanks, I will try when I will get Xcode
